# Poker Consensus Engine - rustfmt configuration

edition = "2021"
array_layout = "vertical"
attr_fn_like_layout = "Vertical"
fn_call_layout = "Vertical"
chain_width = 80
fn_single_line = false
where_single_line = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
normalize_comments = true
wrap_comments = true
comment_width = 100
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_lit_width = "Ignore"
enum_lit_width = "Ignore"
struct_variant_width = "Ignore"
array_width = 80
fn_params_width = 80
# Imports
imports_granularity = "Crate"
reorder_imports = true
# Control flow
force_multiline_blocks = true
# Expressions
group_parenthesized = true
use_field_init_shorthand = true
# Modules
indent_style = "Block"
brace_style = "SameLineWhere"
allow_separate_submod_files = true
